host: localhost
port: 8080
domain: localhost
siteownername: Satoshi
siteownerurl: http://localhost
sitename: Satdress
nostrprivatekey: <nsec>
datadir: </abs/path/to/datadir>

users:
  - name: jane
    kind: phoenix
    host: <ip:port>
    key: <hex>
    nwcsecret: <32-byte-hex>
    nwcrelay: <wss://host>

  - name: alice
    kind: commando
    nodeid: <hex>
    host: <ip:port>
    rune: <base64>

  - name: bob
    kind: lnd
    host: <ip:port>
    key: <macaroon>

  - name: eve
    kind: eclair
    host: <ip:port>

  - name: carlos
    kind: lnpay
    pak: <pak>
    wak: <wak>

  - name: charlie
    kind: lnbits
    host: <ip:port>
    key: <key>

  - name: judy
    kind: sparko
    host: <ip:port>
    key: <key>
